name: Deploy EC2
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: actions/checkout@v2
        with:
          host: 34.207.64.117
          username: ubuntu
          key: ${{ secrets.UAT_KEY }}
          script: sh app.sh
